version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${DBPASS}"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  cartique:
    build: .
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "60000:60000"
  
volumes:
  data: